### ISSUE TITLE
AttributeError: 'Calendar' object has no attribute '_set_event_state'

### ISSUE THREAD

**Issue by Keucar** [methodpark/meeting-room-display#6]
Hello,

i try to build the Software.
O365 connection is O.K, .
The test creates a  "Ad-hoc Meeting" , but  i got some "AttributeError: 'Calendar' object has no attribute '_set_event_state'"

`======================================================================
ERROR: test__cancel_running_adhoc_meeting__deletes_event (test.ou_test.OutlookRoomRepositoryTest.test__cancel_running_adhoc_meeting__deletes_event)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 112, in test__cancel_running_adhoc_meeting__deletes_event
    self.backend.calendar._set_event_state(EventStates.ADHOC)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

======================================================================
ERROR: test__cancel_running_adhoc_meeting__deletes_event_not (test.ou_test.OutlookRoomRepositoryTest.test__cancel_running_adhoc_meeting__deletes_event_not)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 124, in test__cancel_running_adhoc_meeting__deletes_event_not
    self.backend.calendar._set_event_state(EventStates.RUNNING)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

======================================================================
ERROR: test__cancel_running_adhoc_meeting__without_running_event (test.ou_test.OutlookRoomRepositoryTest.test__cancel_running_adhoc_meeting__without_running_event)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 136, in test__cancel_running_adhoc_meeting__without_running_event
    self.backend.calendar._set_event_state(EventStates.FUTURE)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

======================================================================
ERROR: test__fetch_calendar__raises_error (test.ou_test.OutlookRoomRepositoryTest.test__fetch_calendar__raises_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 48, in test__fetch_calendar__raises_error
    self.assertRaises(outlook.AuthenticationFailureError, self.backend.fetch_calendar())
  File "/usr/lib/python3.11/unittest/case.py", line 766, in assertRaises
    return context.handle('assertRaises', args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/case.py", line 237, in handle
    callable_obj(*args, **kwargs)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test__get_appointment__returns_future_event (test.ou_test.OutlookRoomRepositoryTest.test__get_appointment__returns_future_event)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 89, in test__get_appointment__returns_future_event
    self.backend.calendar._set_event_state(EventStates.FUTURE)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

======================================================================
ERROR: test__get_appointment__returns_running_event (test.ou_test.OutlookRoomRepositoryTest.test__get_appointment__returns_running_event)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 66, in test__get_appointment__returns_running_event
    self.backend.calendar._set_event_state(EventStates.RUNNING)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

======================================================================
ERROR: test__get_appointment__returns_upcoming_event (test.ou_test.OutlookRoomRepositoryTest.test__get_appointment__returns_upcoming_event)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 77, in test__get_appointment__returns_upcoming_event
    self.backend.calendar._set_event_state(EventStates.UPCOMING)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

======================================================================
ERROR: test__get_appointment__with_elapsed_event__returns_none (test.ou_test.OutlookRoomRepositoryTest.test__get_appointment__with_elapsed_event__returns_none)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/meeting-room-display/test/ou_test.py", line 57, in test__get_appointment__with_elapsed_event__returns_none
    self.backend.calendar._set_event_state(EventStates.ELAPSED)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calendar' object has no attribute '_set_event_state'

----------------------------------------------------------------------`

**Comment by richard-XV** [comment]
Hello @Keucar,
thank you for reporting this. We will take a look into the issue.
